const PREFIX_SEQUENCE = {
  USERSEQUENCE: {
    USER_MODEL: "USER",
    SEQUENCE: "VYDUSER",
  },
  MEDICINES_SEQUENCE: {
    MEDICINES_MODEL: "Medicine",
    SEQUENCE: "VYDMED",
  },
  TESTS_SEQUENCE: {
    TESTS_MODEL: "PatientTest",
    SEQUENCE: "VYDTEST",
  },
   EPRESCRIPTION_SEQUENCE: {
    EPRESCRIPTION_MODEL: "eprescriptions",
    SEQUENCE: "VYDEPRES",
  },
};

module.exports = PREFIX_SEQUENCE;
